### ISSUE TITLE
catch returns a string and sets a code - should do the opposite

### ISSUE THREAD

**Issue by endofexclusive** [howerj/pickle#13]
Compared to Tcl, it seems like pickle has swapped the meaning of the `catch` command return value and the `varname` parameter.

To be consistent with Tcl and avoid having to learn two command syntaxes, the `catch` command should return a non-zero integer value if the script raised an error. Else `catch` should return `0`. The argument `varname` should always get the result string assigned.

Test case:
```
$ cat /tmp/catch.tcl 
set retcode4 [catch {set a foobar} resultvar4]
puts "retcode4:   expected='0',      actual='$retcode4'"
puts "resultvar4: expected='foobar', actual='$resultvar4'"
puts ""

# this assumes b is NOT already set: we want the error.
set retcode5 [catch {set b} resultvar5]
puts "retcode5:   expected='a non-zero integer value', actual='$retcode5'"
puts "resultvar5: expected='msg about non-existing variable', actual='$resultvar5'"
```

With `tclsh`:
```
$ tclsh /tmp/catch.tcl 
retcode4:   expected='0',      actual='0'
resultvar4: expected='foobar', actual='foobar'

retcode5:   expected='a non-zero integer value', actual='1'
resultvar5: expected='msg about non-existing variable', actual='can't read "b": no such variable'
```

With `pickle`:
```
$ ./pickle /tmp/catch.tcl 
retcode4:   expected='0',      actual='foobar'
resultvar4: expected='foobar', actual='0'

retcode5:   expected='a non-zero integer value', actual='Invalid variable b'
resultvar5: expected='msg about non-existing variable', actual='-1'
```

**Comment by howerj** [comment]
Yes, this is incorrect, I'll fix this tomorrow (most probably). The correct version of catch is also easier to use, so that's an advantage!

**Comment by endofexclusive** [comment]
Cool. Thank you for the confirmation.

**Comment by howerj** [comment]
I don't know if you managed to test the fix for this, I added it a while ago, I'll close this issue anyway, let me know if there are any problems, and thanks!

**Comment by endofexclusive** [comment]
I have tried it now and it works very well.
Making the `resultvar` optional was also a nice improvement.
Thanks
